### ISSUE TITLE
Can't build next-my or IceStorm

### ISSUE THREAD

**Issue by bmentink** [ktemkin/homebrew-oss-fpga#1]
Hi,

The Title was meant to be: Can't build nextpnr or IceStorm (Yosys builds ok)

Tried building as instructions on Powerbook M1, but the build fails when it tries to build gcc dependancy. Erro is:
`==> Installing ktemkin/oss-fpga/nextpnr-ice40 dependency: gcc
==> Patching
==> Applying bigsur.diff
patching file gcc/config/darwin-c.c
patching file gcc/config/darwin-driver.c
==> ../configure --build=x86_64-apple-darwin20 --prefix=/opt/homebrew/Cellar/gcc/10.
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
Last 15 lines from /Users/bmentink/Library/Logs/Homebrew/gcc/02.make:
echo timestamp > stmp-int-hdrs
/private/tmp/gcc-20201204-77211-9abnz9/gcc-10.2.0/build/./gcc/xgcc -B/private/tmp/gcc-20201204-77211-9abnz9/gcc-10.2.0/build/./gcc/ -xc -nostdinc /dev/null -S -o /dev/null -fself-test=../../gcc/testsuite/selftests
/private/tmp/gcc-20201204-77211-9abnz9/gcc-10.2.0/build/./gcc/xgcc -B/private/tmp/gcc-20201204-77211-9abnz9/gcc-10.2.0/build/./gcc/ -xc++ -nostdinc /dev/null -S -o /dev/null -fself-test=../../gcc/testsuite/selftests
cc1: note: self-tests are not enabled in this build
echo timestamp > s-selftest-c
/dev/null:1: internal compiler error: in darwin_gt_pch_use_address, at config/host-darwin.c:51
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make[3]: *** [s-selftest-c++] Error 1
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
`

I had to do: export ARCHFLAGS='-arch arm64' before I could build for ARM

**Comment by bmentink** [comment]
Any idea's ???

**Comment by ktemkin** [comment]
Unless something has changed very recently, there's currently no official working GCC build for M1 machines; due to ABI differences between macOS and Linux on arm64.

You can try installing a hacked up GCC from https://github.com/ktemkin/homebrew-tirepatch, which is what I used to build the tools on my end.

**Comment by ktemkin** [comment]
Closing this as it's an issue with homebrew upstream's `gcc`, and not a local issue. (YMMV with the hacks provided here.)
